language: java
jdk:
  - oraclejdk17
# git strips the wrapper jar file so we have to force its download during the build
install:
  - mvn -N wrapper:wrapper
  - ./mvnw install -Dmaven.javadoc.skip=true -B -V

before_deploy:
  - gem install faraday -v 1.8.0

deploy:
  provider: heroku
  api_key:
    secure: "ENCRYPTED_API_KEY"