language: java
jdk:
  - oraclejdk17
# git strips the wrapper jar file so we have to force its download during the build
install:
  - mvn -N wrapper:wrapper
  - ./mvnw install -Dmaven.javadoc.skip=true -B -V
#  - gem install faraday -v 1.8.0


#before_deploy:
#  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0

deploy:
  provider: heroku
  api_key:
    secure: d7f8f2cb-005c-4d5b-ac43-a3764e2cc9fd
