spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://127.0.0.1:5433/items
    hikari:
      idleTimeout: 30000
      maximumPoolSize: 10
session:
  cookie:
    max:
      age: 14400
