version: '3.8'

services:

  postgres-database:
    build: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgres/data

volumes:
  db: