version: '3.8'

services:

  mysql-database:
    build: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - db:/var/lib/minesql/data

volumes:
  db: